apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memory-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: memory-service.soulism.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memory-service
                port:
                  number: 3002
