apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audit-ledger-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: audit-ledger-service.soulism.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: audit-ledger-service
                port:
                  number: 4003
