apiVersion: v1
kind: Service
metadata:
  name: audit-ledger-service
  labels:
    app: audit-ledger-service
spec:
  selector:
    app: audit-ledger-service
  ports:
    - name: http
      protocol: TCP
      port: 4003
      targetPort: 4003
  type: ClusterIP
